import plotly.graph_objects as go

# =============================================================================
# üé® PROFESSIONAL COLOR PALETTE (Industry Standard)
# =============================================================================
C_STEEL_DARK = "#1e293b"    # ‡∏Ç‡∏≠‡∏ö‡πÄ‡∏´‡∏•‡πá‡∏Å‡πÄ‡∏Ç‡πâ‡∏°
C_STEEL_LIGHT = "#f8fafc"   # ‡∏™‡∏µ‡∏ú‡∏¥‡∏ß‡πÄ‡∏´‡∏•‡πá‡∏Å (Galvanized look)
C_PLATE = "#0284c7"         # ‡∏™‡∏µ‡πÄ‡∏û‡∏•‡∏ó (Deep Sky Blue)
C_BOLT = "#be123c"          # ‡∏™‡∏µ‡πÇ‡∏ö‡∏•‡∏ó‡πå (Crimson)
C_WELD = "#94a3b8"          # ‡∏™‡∏µ‡∏£‡∏≠‡∏¢‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°
C_DIM = "#334155"           # ‡∏™‡∏µ‡πÄ‡∏™‡πâ‡∏ô Dimension
C_YELLOW_COL = "#eab308"    # ‡πÄ‡∏™‡πâ‡∏ô‡∏Ç‡∏≠‡∏ö‡πÄ‡∏Ç‡∏ï‡πÄ‡∏™‡∏≤ (Yellow Line)

# =============================================================================
# üõ†Ô∏è ADVANCED HELPERS
# =============================================================================
def add_weld_symbol(fig, x, y, size=8, side="left"):
    """ ‡∏ß‡∏≤‡∏î‡∏™‡∏±‡∏ç‡∏•‡∏±‡∏Å‡∏©‡∏ì‡πå‡∏£‡∏≠‡∏¢‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏° Fillet Weld """
    sign = -1 if side == "left" else 1
    fig.add_trace(go.Scatter(
        x=[x, x, x + (sign * size), x],
        y=[y - size, y, y, y - size],
        fill="toself", fillcolor=C_WELD, line=dict(color=C_STEEL_DARK, width=0.5),
        mode='lines', hoverinfo='skip', showlegend=False
    ))

def get_i_section_path(x_center, y_center, h, b, tf, tw, r=10):
    """ ‡∏™‡∏£‡πâ‡∏≤‡∏á‡πÄ‡∏™‡πâ‡∏ô‡∏£‡∏≠‡∏ö‡∏£‡∏π‡∏õ I-Section ‡πÅ‡∏ö‡∏ö‡∏°‡∏µ Root Radius (‡∏Ñ‡∏ß‡∏≤‡∏°‡πÇ‡∏Ñ‡πâ‡∏á‡πÇ‡∏Ñ‡∏ô‡∏õ‡∏µ‡∏Å) """
    # ‡∏Ñ‡∏≥‡∏ô‡∏ß‡∏ì‡∏û‡∏¥‡∏Å‡∏±‡∏î‡∏à‡∏∏‡∏î‡πÇ‡∏Ñ‡πâ‡∏á‡πÄ‡∏û‡∏∑‡πà‡∏≠‡πÉ‡∏´‡πâ‡πÄ‡∏´‡∏°‡∏∑‡∏≠‡∏ô‡πÄ‡∏´‡∏•‡πá‡∏Å‡∏à‡∏£‡∏¥‡∏á‡∏ó‡∏µ‡πà‡∏™‡∏∏‡∏î
    return (f"M {x_center-b/2},{y_center-h/2} L {x_center+b/2},{y_center-h/2} "
            f"L {x_center+b/2},{y_center-h/2+tf} L {x_center+tw/2+r},{y_center-h/2+tf} "
            f"Q {x_center+tw/2},{y_center-h/2+tf} {x_center+tw/2},{y_center-h/2+tf+r} "
            f"L {x_center+tw/2},{y_center+h/2-tf-r} "
            f"Q {x_center+tw/2},{y_center+h/2-tf} {x_center+tw/2+r},{y_center+h/2-tf} "
            f"L {x_center+b/2},{y_center+h/2-tf} L {x_center+b/2},{y_center+h/2} "
            f"L {x_center-b/2},{y_center+h/2} L {x_center-b/2},{y_center+h/2-tf} "
            f"L {x_center-tw/2-r},{y_center+h/2-tf} "
            f"Q {x_center-tw/2},{y_center+h/2-tf} {x_center-tw/2},{y_center+h/2-tf-r} "
            f"L {x_center-tw/2},{y_center-h/2+tf+r} "
            f"Q {x_center-tw/2},{y_center-h/2+tf} {x_center-tw/2-r},{y_center-h/2+tf} "
            f"L {x_center-b/2},{y_center-h/2+tf} Z")

# =============================================================================
# 3. SIDE VIEW (SECTION) - ‡∏≠‡∏±‡∏õ‡πÄ‡∏Å‡∏£‡∏î‡∏Ñ‡∏ß‡∏≤‡∏°‡∏•‡∏∞‡πÄ‡∏≠‡∏µ‡∏¢‡∏î‡∏™‡∏π‡∏á‡∏™‡∏∏‡∏î
# =============================================================================
def create_side_view(beam, plate, bolts):
    fig = go.Figure()
    h, b, tf, tw = beam['h'], beam['b'], beam['tf'], beam['tw']
    h_pl, t_pl = plate['h'], plate['t']
    lv = plate.get('lv', bolts.get('lv', 35))
    n_rows, s_v = bolts['rows'], bolts['s_v']

    # --- 1. COLUMN BOUNDARY (‡πÄ‡∏™‡πâ‡∏ô‡πÄ‡∏´‡∏•‡∏∑‡∏≠‡∏á - ‡∏Ñ‡∏ß‡∏≤‡∏°‡∏Å‡∏ß‡πâ‡∏≤‡∏á‡πÄ‡∏™‡∏≤) ---
    b_col = b + 40
    fig.add_shape(type="rect", x0=-b_col/2, y0=-h/2-60, x1=b_col/2, y1=h/2+60, 
                  line=dict(color=C_YELLOW_COL, width=2.5, dash="dash"), fillcolor="rgba(248, 250, 252, 0.5)")

    # --- 2. BEAM I-SECTION WITH ROOT RADIUS ---
    beam_path = get_i_section_path(0, 0, h, b, tf, tw, r=12)
    fig.add_shape(type="path", path=beam_path, fillcolor=C_STEEL_LIGHT, line=dict(color=C_STEEL_DARK, width=2))

    # --- 3. SHEAR PLATE & BOLTS ---
    # ‡∏£‡∏∞‡∏¢‡∏∞ Clearance ‡∏£‡∏∞‡∏´‡∏ß‡πà‡∏≤‡∏á Web ‡∏Å‡∏±‡∏ö Plate (‡∏™‡∏°‡∏°‡∏ï‡∏¥ 2mm)
    p_x0 = tw/2
    p_x1 = p_x0 + t_pl
    fig.add_shape(type="rect", x0=p_x0, y0=-h_pl/2, x1=p_x1, y1=h_pl/2, 
                  fillcolor=C_PLATE, line=dict(color=C_STEEL_DARK, width=1.5))
    
    # ‡∏ß‡∏≤‡∏î Bolt ‡∏û‡∏£‡πâ‡∏≠‡∏°‡∏´‡∏±‡∏ß‡∏ô‡πá‡∏≠‡∏ï‡πÅ‡∏•‡∏∞‡πÅ‡∏´‡∏ß‡∏ô (Hex Bolt Detail)
    for i in range(n_rows):
        y_bolt = h_pl/2 - lv - (i * s_v)
        # Shank
        fig.add_shape(type="rect", x0=p_x1, y0=y_bolt-5, x1=p_x1+15, y1=y_bolt+5, fillcolor=C_BOLT, line_width=0.5)
        # Nut
        fig.add_shape(type="rect", x0=p_x1+10, y0=y_bolt-8, x1=p_x1+18, y1=y_bolt+8, fillcolor="#4b5563", line_width=1)

    # --- 4. WELDING DETAILS ---
    # ‡∏£‡∏≠‡∏¢‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°‡∏£‡∏∞‡∏´‡∏ß‡πà‡∏≤‡∏á Plate ‡∏Å‡∏±‡∏ö‡∏´‡∏ô‡πâ‡∏≤‡πÄ‡∏™‡∏≤ (‡∏ï‡∏≤‡∏°‡∏ó‡∏µ‡πà‡∏Ñ‡∏∏‡∏ì‡∏≠‡∏ò‡∏¥‡∏ö‡∏≤‡∏¢‡∏ß‡πà‡∏≤ Plate ‡πÄ‡∏ä‡∏∑‡πà‡∏≠‡∏°‡πÄ‡∏™‡∏≤)
    add_weld_symbol(fig, p_x0, h_pl/2, size=10, side="left")
    add_weld_symbol(fig, p_x0, -h_pl/2 + 10, size=10, side="left")

    # --- 5. DIMENSIONING ---
    from drawing_utils import add_cad_dim # ‡πÄ‡∏£‡∏µ‡∏¢‡∏Å‡πÉ‡∏ä‡πâ‡∏ü‡∏±‡∏á‡∏Å‡πå‡∏ä‡∏±‡∏ô‡πÄ‡∏î‡∏¥‡∏°‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì
    add_cad_dim(fig, -b/2, h/2+15, b/2, h/2+15, f"BEAM B={int(b)}", offset=25)
    add_cad_dim(fig, b/2+25, h/2, b/2+25, -h/2, f"BEAM H={int(h)}", "vert", offset=40)

    fig.update_layout(
        title=dict(text="<b>DETAILED SECTION VIEW</b>", font=dict(size=16)),
        plot_bgcolor="white", height=500, width=500,
        xaxis=dict(visible=False, range=[-b_col*0.8, b_col*1.2]),
        yaxis=dict(visible=False, scaleanchor="x", scaleratio=1),
        margin=dict(l=20, r=20, t=50, b=20)
    )
    return fig

# ‡∏´‡∏°‡∏≤‡∏¢‡πÄ‡∏´‡∏ï‡∏∏: ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö create_plan_view ‡πÅ‡∏•‡∏∞ create_front_view ‡πÉ‡∏´‡πâ‡∏Ñ‡∏á‡πÇ‡∏Ñ‡πâ‡∏î‡πÄ‡∏î‡∏¥‡∏°‡πÑ‡∏ß‡πâ 
# ‡πÄ‡∏û‡∏∑‡πà‡∏≠‡∏Ñ‡∏ß‡∏≤‡∏°‡πÄ‡∏™‡∏ñ‡∏µ‡∏¢‡∏£‡∏Ç‡∏≠‡∏á‡πÅ‡∏≠‡∏õ‡∏û‡∏•‡∏¥‡πÄ‡∏Ñ‡∏ä‡∏±‡∏ô
