# report_generator.py
import streamlit as st
import streamlit.components.v1 as components

def render_report_tab(method, is_lrfd, sec_name, steel_grade, p, res, bolt):
    """
    Renders a professional design calculation report.
    - p: section properties dictionary (h, b, tw, tf, Ix, Zx, Sx)
    - res: calculation results (capacities, ratios, ltb_info)
    - bolt: connection details
    """
    
    # 1. Extract Calculation Data
    w_safe = res.get('w_safe', 0)
    cause = res.get('cause', 'N/A')
    v_act = res.get('v_act', 0)
    v_cap = res.get('v_cap', 1)
    m_act = res.get('m_act', 0)
    m_cap = res.get('m_cap', 1)  # Expected in kg-m from the results_context
    d_act = res.get('d_act', 0)
    d_all = res.get('d_all', 1)
    
    # 2. Extract LTB Data (for technical transparency)
    ltb = res.get('ltb_info', {})
    lb_m = ltb.get('Lb', 0) / 100
    lp_m = ltb.get('Lp', 0) / 100
    lr_m = ltb.get('Lr', 0) / 100

    # 3. Construct HTML/CSS Report
    html_content = f"""
    <div id="report-container" style="background-color:#ffffff; padding:40px; border-radius:10px; border:1px solid #d1d5db; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color:#111827; max-width: 900px; margin: auto;">
        
        <div style="border-bottom:3px solid #1e40af; margin-bottom:20px; padding-bottom:10px; display: flex; justify-content: space-between; align-items: flex-end;">
            <div>
                <h1 style="margin:0; color:#1e40af; font-size: 28px;">STRUCTURAL DESIGN REPORT</h1>
                <p style="margin:0; font-size:14px; color:#6b7280;">Steel Beam Verification per AISC 360 ({method})</p>
            </div>
            <div style="text-align: right;">
                <p style="margin:0; font-weight:bold;">Project: Beam Insight Analysis</p>
                <p style="margin:0; font-size:12px;">Generated by Gemini Hybrid Engine</p>
            </div>
        </div>

        <div style="margin-bottom:25px;">
            <h4 style="color:#1e40af; border-left: 5px solid #1e40af; padding-left: 10px; margin-bottom:10px;">1. DESIGN SUMMARY</h4>
            <table style="width:100%; border-collapse:collapse; font-size:14px;">
                <tr>
                    <td style="padding:10px; background:#f3f4f6; font-weight:bold; border:1px solid #e5e7eb; width:30%;">Selected Section</td>
                    <td style="padding:10px; border:1px solid #e5e7eb;">{sec_name} ({steel_grade})</td>
                </tr>
                <tr>
                    <td style="padding:10px; background:#f3f4f6; font-weight:bold; border:1px solid #e5e7eb;">Max Allowable Load</td>
                    <td style="padding:10px; border:1px solid #e5e7eb; color:#1e40af; font-weight:bold; font-size:18px;">{w_safe:,.2f} kg/m</td>
                </tr>
                <tr>
                    <td style="padding:10px; background:#f3f4f6; font-weight:bold; border:1px solid #e5e7eb;">Governing Limit State</td>
                    <td style="padding:10px; border:1px solid #e5e7eb; font-weight:bold; color:#dc2626;">{cause}</td>
                </tr>
            </table>
        </div>

        <div style="margin-bottom:25px;">
            <h4 style="color:#1e40af; border-left: 5px solid #1e40af; padding-left: 10px; margin-bottom:10px;">2. SECTION PROPERTIES</h4>
            
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                <table style="width:100%; border-collapse:collapse; font-size:13px;">
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Depth (h)</td><td style="text-align:right;">{p['h']} mm</td></tr>
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Width (b)</td><td style="text-align:right;">{p['b']} mm</td></tr>
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Web Thickness (tw)</td><td style="text-align:right;">{p['tw']} mm</td></tr>
                </table>
                <table style="width:100%; border-collapse:collapse; font-size:13px;">
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Inertia (Ix)</td><td style="text-align:right;">{p['Ix']:,.0f} cm⁴</td></tr>
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Section Modulus (Sx)</td><td style="text-align:right;">{p['Sx']:,.0f} cm³</td></tr>
                    <tr><td style="padding:5px; border-bottom:1px solid #eee;">Plastic Modulus (Zx)</td><td style="text-align:right;">{p['Zx']:,.0f} cm³</td></tr>
                </table>
            </div>
        </div>

        <h4 style="color:#1e40af; border-left: 5px solid #1e40af; padding-left: 10px; margin-bottom:10px;">3. CAPACITY VERIFICATION</h4>
        <table style="width:100%; border-collapse:collapse; text-align:center; font-size:14px; margin-bottom:20px;">
            <thead>
                <tr style="background:#1e40af; color:white;">
                    <th style="padding:12px; border:1px solid #e5e7eb;">Check Item</th>
                    <th style="padding:12px; border:1px solid #e5e7eb;">Demand (Ru)</th>
                    <th style="padding:12px; border:1px solid #e5e7eb;">Capacity (Rn)</th>
                    <th style="padding:12px; border:1px solid #e5e7eb;">Utilization</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="padding:12px; border:1px solid #e5e7eb; text-align:left;">Shear Strength</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{v_act:,.0f} kg</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{v_cap:,.0f} kg</td>
                    <td style="padding:12px; border:1px solid #e5e7eb; font-weight:bold; color:{(v_act/v_cap > 1.0) and '#dc2626' or '#16a34a'};">{(v_act/v_cap):.3f}</td>
                </tr>
                <tr>
                    <td style="padding:12px; border:1px solid #e5e7eb; text-align:left;">Bending Moment (LTB)</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{m_act:,.0f} kg.m</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{m_cap:,.0f} kg.m</td>
                    <td style="padding:12px; border:1px solid #e5e7eb; font-weight:bold; color:{(m_act/m_cap > 1.0) and '#dc2626' or '#16a34a'};">{(m_act/m_cap):.3f}</td>
                </tr>
                <tr>
                    <td style="padding:12px; border:1px solid #e5e7eb; text-align:left;">Deflection</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{d_act:.3f} cm</td>
                    <td style="padding:12px; border:1px solid #e5e7eb;">{d_all:.3f} cm</td>
                    <td style="padding:12px; border:1px solid #e5e7eb; font-weight:bold; color:{(d_act/d_all > 1.0) and '#dc2626' or '#16a34a'};">{(d_act/d_all):.3f}</td>
                </tr>
            </tbody>
        </table>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
            <div>
                <h4 style="color:#1e40af; border-left: 5px solid #1e40af; padding-left: 10px; margin-bottom:10px;">4. STABILITY (LTB)</h4>
                <div style="font-size: 13px; line-height: 1.6;">
                    Unbraced Length (Lb): <b>{lb_m:.2f} m</b><br>
                    Plastic Limit (Lp): <b>{lp_m:.2f} m</b><br>
                    Elastic Limit (Lr): <b>{lr_m:.2f} m</b><br>
                    Stability Zone: <b>{ltb.get('Zone', 'N/A')}</b>
                </div>
            </div>
            <div>
                <h4 style="color:#1e40af; border-left: 5px solid #1e40af; padding-left: 10px; margin-bottom:10px;">5. CONNECTION</h4>
                
                <div style="font-size: 13px; line-height: 1.6;">
                    Type: <b>{bolt.get('type', 'N/A')}</b><br>
                    Bolt: <b>{bolt.get('grade', 'N/A')} - {bolt.get('size', 'N/A')}</b><br>
                    Design Shear (Vd): <b>{res.get('v_conn_design', 0):,.0f} kg</b>
                </div>
            </div>
        </div>

        <div style="margin-top:40px; border-top:1px solid #e5e7eb; padding-top:10px; font-size:11px; color:#9ca3af; text-align:center;">
            This report is a computer-generated preliminary calculation. Final design should be verified by a licensed Professional Engineer.
        </div>
    </div>
    
    <div style="text-align:center; margin-top:20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background-color: #1e40af; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold;">
            🖨️ Print Report to PDF
        </button>
    </div>
    """

    # 4. Render Component
    components.html(html_content, height=1100, scrolling=True)
