import streamlit as st

def render_report_tab(method, is_lrfd, sec_name, fy, p, res, bolt):
    # รวม HTML ทั้งหมดไว้ในตัวแปรเดียว เพื่อความเป็นระเบียบ
    html_template = f"""
    <div style="font-family: 'Sarabun', sans-serif; background-color: #ffffff; padding: 40px; border-radius: 10px; border: 1px solid #dee2e6; box-shadow: 0 4px 6px rgba(0,0,0,0.05); max-width: 850px; margin: auto;">
        
        <div style="display: flex; justify-content: space-between; border-bottom: 3px solid #1e40af; padding-bottom: 15px; margin-bottom: 25px;">
            <div style="text-align: left;">
                <h2 style="margin: 0; color: #1e40af; text-transform: uppercase; letter-spacing: 1px;">Structural Calculation Report</h2>
                <span style="color: #64748b; font-size: 14px;">Generated by Beam Insight System V12</span>
            </div>
            <div style="text-align: right; color: #64748b; font-size: 14px;">
                Date: 15/01/2026<br>
                Method: <b>{method}</b>
            </div>
        </div>

        <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; border-left: 6px solid #1e40af; margin-bottom: 25px;">
            <h4 style="margin-top: 0; color: #1e3a8a; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">1. DESIGN SUMMARY</h4>
            <table style="width: 100%; font-size: 16px;">
                <tr>
                    <td style="color: #475569;">Governing Safe Load:</td>
                    <td style="text-align: right;"><b style="font-size: 22px; color: #dc2626;">{res['w_safe']:,.0f} kg/m</b></td>
                </tr>
                <tr>
                    <td style="color: #475569;">Controlling Factor:</td>
                    <td style="text-align: right; font-weight: bold; color: #1e40af; text-transform: uppercase;">{res['cause']}</td>
                </tr>
            </table>
        </div>

        <h4 style="color: #1e3a8a; margin-bottom: 10px;">2. VERIFICATION DETAILS</h4>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr style="background-color: #f1f5f9;">
                <th style="border: 1px solid #cbd5e1; padding: 12px; text-align: left;">Category</th>
                <th style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">Capacity</th>
                <th style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">Actual</th>
                <th style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">Status</th>
            </tr>
            <tr>
                <td style="border: 1px solid #cbd5e1; padding: 12px;">Shear Resistance</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">{res['v_cap']:,.0f} kg</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">{res['v_act']:,.0f} kg</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center; color: #16a34a; font-weight: bold;">PASS</td>
            </tr>
            <tr>
                <td style="border: 1px solid #cbd5e1; padding: 12px;">Bending Moment</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">{res['m_cap']/100:,.0f} kg.m</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center;">{res['m_act']:,.0f} kg.m</td>
                <td style="border: 1px solid #cbd5e1; padding: 12px; text-align: center; color: #16a34a; font-weight: bold;">PASS</td>
            </tr>
        </table>

        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px;">
            This document is a computer-generated report. No signature is required.
        </div>
    </div>
    """
    # สั่งให้ Streamlit แสดงผลเป็น HTML แบบสมบูรณ์
    st.markdown(html_template, unsafe_allow_html=True)
